// <auto-generated />
namespace MySite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview7-19363-02")]
    public sealed partial class db122 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db122));
        
        string IMigrationMetadata.Id
        {
            get { return "201911081206542_db122"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
